"""empty message

Revision ID: 08e59d9f526e
Revises: f2bb313c0aff
Create Date: 2020-05-30 19:51:20.224574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e59d9f526e'
down_revision = 'f2bb313c0aff'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courier', 'cour_id',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               autoincrement=True)
    op.alter_column('delivers_to', 'deliv_id',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               autoincrement=True)
    op.alter_column('items', 'item_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               autoincrement=True)
    op.alter_column('items', 'spm_id',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('orders', 'acc_num',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('orders', 'order_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               autoincrement=True)
    op.alter_column('payment', 'order_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('payment', 'pay_id',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               autoincrement=True)
    op.alter_column('review', 'acc_num',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer())
    op.alter_column('review', 'item_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer())
    op.alter_column('shopping_cart', 'acc_num',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('shopping_cart', 'cart_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               autoincrement=True)
    op.alter_column('shopping_list', 'item_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('shopping_list', 'list_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               autoincrement=True)
    op.alter_column('supermarket', 'spm_id',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               autoincrement=True)
    op.alter_column('usi', 'acc_num',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer())
    op.alter_column('usi', 'cart_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer())
    op.alter_column('usi', 'item_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer())
    op.alter_column('usr', 'acc_num',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usr', 'acc_num',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               autoincrement=True)
    op.alter_column('usi', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20))
    op.alter_column('usi', 'cart_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20))
    op.alter_column('usi', 'acc_num',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20))
    op.alter_column('supermarket', 'spm_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               autoincrement=True)
    op.alter_column('shopping_list', 'list_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               autoincrement=True)
    op.alter_column('shopping_list', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('shopping_cart', 'cart_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               autoincrement=True)
    op.alter_column('shopping_cart', 'acc_num',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('review', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20))
    op.alter_column('review', 'acc_num',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20))
    op.alter_column('payment', 'pay_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               autoincrement=True)
    op.alter_column('payment', 'order_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('orders', 'order_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               autoincrement=True)
    op.alter_column('orders', 'acc_num',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('items', 'spm_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('items', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               autoincrement=True)
    op.alter_column('delivers_to', 'deliv_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               autoincrement=True)
    op.alter_column('courier', 'cour_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               autoincrement=True)
    # ### end Alembic commands ###

