"""empty message

Revision ID: 16a1d43e73d1
Revises: 0511c81c67b1
Create Date: 2020-04-21 09:04:08.446309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a1d43e73d1'
down_revision = '0511c81c67b1'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_acc_num', table_name='items')
    op.drop_constraint('items_acc_num_fkey', 'items', type_='foreignkey')
    op.drop_column('items', 'acc_num')
    op.add_column('usr', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usr', 'password')
    op.add_column('items', sa.Column('acc_num', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_foreign_key('items_acc_num_fkey', 'items', 'usr', ['acc_num'], ['acc_num'])
    op.create_index('ix_items_acc_num', 'items', ['acc_num'], unique=False)
    # ### end Alembic commands ###

