"""empty message

Revision ID: 17ca0ba63999
Revises: c1aa9f185949
Create Date: 2020-04-09 12:29:36.770001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ca0ba63999'
down_revision = 'c1aa9f185949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivers_to',
    sa.Column('deliv_id', sa.String(length=10), nullable=False),
    sa.Column('d_type', sa.String(length=10), nullable=True),
    sa.Column('deliv_time', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('deliv_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivers_to')
    # ### end Alembic commands ###
