"""empty message

Revision ID: 27b1ee00cd5d
Revises: 6f25a5db0f52
Create Date: 2020-06-02 09:45:45.262524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27b1ee00cd5d'
down_revision = '6f25a5db0f52'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usi_cart_id', table_name='usi')
    op.drop_index('ix_usi_item_id', table_name='usi')
    op.drop_table('usi')
    op.drop_index('ix_items_spm_id', table_name='items')
    op.drop_table('items')
    op.drop_index('ix_shopping_list_item_id', table_name='shopping_list')
    op.drop_table('shopping_list')
    op.drop_index('ix_review_item_id', table_name='review')
    op.drop_table('review')
    op.add_column('courier', sa.Column('location', sa.String(length=100), nullable=True))
    op.drop_column('courier', 'loc')
    op.add_column('shopping_cart', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_cart', 'date_created')
    op.add_column('courier', sa.Column('loc', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('courier', 'location')
    op.create_table('review',
    sa.Column('acc_num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ratings', postgresql.ENUM('1', '2', '3', '4', '5', name='rating_levels'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['acc_num'], ['usr.acc_num'], name='review_acc_num_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], name='review_item_id_fkey'),
    sa.PrimaryKeyConstraint('acc_num', 'item_id', name='review_pkey')
    )
    op.create_index('ix_review_item_id', 'review', ['item_id'], unique=False)
    op.create_table('shopping_list',
    sa.Column('list_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], name='shopping_list_item_id_fkey'),
    sa.PrimaryKeyConstraint('list_id', name='shopping_list_pkey')
    )
    op.create_index('ix_shopping_list_item_id', 'shopping_list', ['item_id'], unique=False)
    op.create_table('items',
    sa.Column('item_id', sa.INTEGER(), server_default=sa.text("nextval('items_item_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('desc_item', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('i_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exp_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('spm_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['spm_id'], ['supermarket.spm_id'], name='items_spm_id_fkey'),
    sa.PrimaryKeyConstraint('item_id', name='items_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_items_spm_id', 'items', ['spm_id'], unique=False)
    op.create_table('usi',
    sa.Column('acc_num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['acc_num'], ['usr.acc_num'], name='usi_acc_num_fkey'),
    sa.ForeignKeyConstraint(['cart_id'], ['shopping_cart.cart_id'], name='usi_cart_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], name='usi_item_id_fkey'),
    sa.PrimaryKeyConstraint('acc_num', 'item_id', 'cart_id', name='usi_pkey')
    )
    op.create_index('ix_usi_item_id', 'usi', ['item_id'], unique=False)
    op.create_index('ix_usi_cart_id', 'usi', ['cart_id'], unique=False)
    # ### end Alembic commands ###

