"""empty message

Revision ID: 2e25a2d58a97
Revises: 37de9b1ed7c3
Create Date: 2020-06-18 16:55:54.841199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e25a2d58a97'
down_revision = '37de9b1ed7c3'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cart_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_cart_id'), 'orders', ['cart_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'shopping_cart', ['cart_id'], ['cart_id'])
    # ### end Alembic commands ###


def downgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_cart_id'), table_name='orders')
    op.drop_column('orders', 'cart_id')
    # ### end Alembic commands ###

