"""empty message

Revision ID: 34a0b698d225
Revises: 17ca0ba63999
Create Date: 2020-04-10 14:54:43.043528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a0b698d225'
down_revision = '17ca0ba63999'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivers_to',
    sa.Column('deliv_id', sa.String(length=10), nullable=False),
    sa.Column('d_type', sa.String(length=10), nullable=True),
    sa.Column('deliv_time', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('deliv_id')
    )
    # ### end Alembic commands ###


def downgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivers_to')
    # ### end Alembic commands ###

