"""empty message

Revision ID: 38d414136250
Revises: 08e59d9f526e
Create Date: 2020-05-31 15:49:50.644965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d414136250'
down_revision = '08e59d9f526e'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivers_to',
    sa.Column('deliv_id', sa.Integer(), nullable=False),
    sa.Column('d_type', sa.String(length=10), nullable=True),
    sa.Column('deliv_time', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('deliv_id')
    )
    op.create_table('supermarket',
    sa.Column('spm_id', sa.Integer(), nullable=False),
    sa.Column('spm_name', sa.String(length=60), nullable=True),
    sa.Column('street', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('branch', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('spm_id')
    )
    op.create_index(op.f('ix_supermarket_spm_name'), 'supermarket', ['spm_name'], unique=True)
    op.create_table('usr',
    sa.Column('acc_num', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=20), nullable=True),
    sa.Column('lname', sa.String(length=20), nullable=True),
    sa.Column('sex', sa.String(length=6), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hh_size', sa.String(length=6), nullable=True),
    sa.Column('no_adults', sa.String(length=6), nullable=True),
    sa.Column('no_kids', sa.String(length=6), nullable=True),
    sa.Column('marital_s', sa.String(length=10), nullable=True),
    sa.Column('diet_pref', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('acc_num')
    )
    op.create_table('courier',
    sa.Column('cour_id', sa.Integer(), nullable=False),
    sa.Column('cour_name', sa.String(length=100), nullable=True),
    sa.Column('spm_name', sa.String(length=60), nullable=True),
    sa.Column('loc', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['spm_name'], ['supermarket.spm_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cour_id')
    )
    op.create_index(op.f('ix_courier_spm_name'), 'courier', ['spm_name'], unique=True)
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=True),
    sa.Column('price', sa.String(length=10), nullable=True),
    sa.Column('brand', sa.String(length=30), nullable=True),
    sa.Column('desc_item', sa.String(length=100), nullable=True),
    sa.Column('i_type', sa.String(length=30), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.Column('exp_date', sa.String(length=20), nullable=True),
    sa.Column('spm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spm_id'], ['supermarket.spm_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_items_spm_id'), 'items', ['spm_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('acc_num', sa.Integer(), nullable=True),
    sa.Column('deliv_time', sa.String(length=100), nullable=True),
    sa.Column('sale_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['acc_num'], ['usr.acc_num'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_acc_num'), 'orders', ['acc_num'], unique=False)
    op.create_table('shopping_cart',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('acc_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acc_num'], ['usr.acc_num'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_index(op.f('ix_shopping_cart_acc_num'), 'shopping_cart', ['acc_num'], unique=False)
    op.create_table('payment',
    sa.Column('pay_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('p_time', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pay_id')
    )
    op.create_index(op.f('ix_payment_order_id'), 'payment', ['order_id'], unique=False)
    op.create_table('review',
    sa.Column('acc_num', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('ratings', sa.Enum('1', '2', '3', '4', '5', name='rating_levels'), nullable=True),
    sa.ForeignKeyConstraint(['acc_num'], ['usr.acc_num'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('acc_num', 'item_id')
    )
    op.create_index(op.f('ix_review_item_id'), 'review', ['item_id'], unique=False)
    op.create_table('shopping_list',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('list_id')
    )
    op.create_index(op.f('ix_shopping_list_item_id'), 'shopping_list', ['item_id'], unique=False)
    op.create_table('usi',
    sa.Column('acc_num', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acc_num'], ['usr.acc_num'], ),
    sa.ForeignKeyConstraint(['cart_id'], ['shopping_cart.cart_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('acc_num', 'item_id', 'cart_id')
    )
    op.create_index(op.f('ix_usi_cart_id'), 'usi', ['cart_id'], unique=False)
    op.create_index(op.f('ix_usi_item_id'), 'usi', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usi_item_id'), table_name='usi')
    op.drop_index(op.f('ix_usi_cart_id'), table_name='usi')
    op.drop_table('usi')
    op.drop_index(op.f('ix_shopping_list_item_id'), table_name='shopping_list')
    op.drop_table('shopping_list')
    op.drop_index(op.f('ix_review_item_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_payment_order_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_shopping_cart_acc_num'), table_name='shopping_cart')
    op.drop_table('shopping_cart')
    op.drop_index(op.f('ix_orders_acc_num'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_items_spm_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_courier_spm_name'), table_name='courier')
    op.drop_table('courier')
    op.drop_table('usr')
    op.drop_index(op.f('ix_supermarket_spm_name'), table_name='supermarket')
    op.drop_table('supermarket')
    op.drop_table('delivers_to')
    # ### end Alembic commands ###

