"""empty message

Revision ID: 52d32b7e0a99
Revises: 72a69e4e15ce
Create Date: 2020-06-08 04:58:54.909800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d32b7e0a99'
down_revision = '72a69e4e15ce'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('department', sa.String(length=50), nullable=True))
    op.add_column('items', sa.Column('size', sa.String(length=25), nullable=True))
    op.alter_column('items', 'desc_item',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('items', 'price')
    # ### end Alembic commands ###


def downgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('price', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('items', 'desc_item',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('items', 'size')
    op.drop_column('items', 'department')
    # ### end Alembic commands ###

