"""empty message

Revision ID: 844af4b9482d
Revises: 8f8129965c98
Create Date: 2020-06-18 17:01:58.940519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844af4b9482d'
down_revision = '8f8129965c98'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('date_ordered', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'deliv_time',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'deliv_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('orders', 'date_ordered')
    # ### end Alembic commands ###

