"""empty message

Revision ID: a74966cc848e
Revises: ef77ede9bf45
Create Date: 2020-06-08 07:39:57.842802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a74966cc848e'
down_revision = 'ef77ede9bf45'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_items',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_list.list_id'], ),
    sa.PrimaryKeyConstraint('list_id', 'item_id')
    )
    op.create_index(op.f('ix_list_items_item_id'), 'list_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_list_items_list_id'), 'list_items', ['list_id'], unique=False)
    op.drop_index('ix_list_item_item_id', table_name='list_item')
    op.drop_index('ix_list_item_list_id', table_name='list_item')
    op.drop_table('list_item')
    op.add_column('shopping_list', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list', 'name')
    op.create_table('list_item',
    sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], name='list_item_item_id_fkey'),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_list.list_id'], name='list_item_list_id_fkey'),
    sa.PrimaryKeyConstraint('list_id', 'item_id', name='list_item_pkey')
    )
    op.create_index('ix_list_item_list_id', 'list_item', ['list_id'], unique=False)
    op.create_index('ix_list_item_item_id', 'list_item', ['item_id'], unique=False)
    op.drop_index(op.f('ix_list_items_list_id'), table_name='list_items')
    op.drop_index(op.f('ix_list_items_item_id'), table_name='list_items')
    op.drop_table('list_items')
    # ### end Alembic commands ###

