"""empty message

Revision ID: a8ec4af23848
Revises: d2a9a693f233
Create Date: 2020-07-02 15:13:20.218613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ec4af23848'
down_revision = 'd2a9a693f233'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_items',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_list.list_id'], ),
    sa.PrimaryKeyConstraint('list_id', 'item_id')
    )
    op.create_index(op.f('ix_list_items_item_id'), 'list_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_list_items_list_id'), 'list_items', ['list_id'], unique=False)
    op.add_column('orders', sa.Column('date_ordered', sa.DateTime(), nullable=True))
    op.drop_index('ix_shopping_list_list_id', table_name='shopping_list')
    # ### end Alembic commands ###


def downgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_shopping_list_list_id', 'shopping_list', ['list_id'], unique=False)
    op.drop_column('orders', 'date_ordered')
    op.drop_index(op.f('ix_list_items_list_id'), table_name='list_items')
    op.drop_index(op.f('ix_list_items_item_id'), table_name='list_items')
    op.drop_table('list_items')
    # ### end Alembic commands ###

