"""empty message

Revision ID: ef77ede9bf45
Revises: 068ac36572fc
Create Date: 2020-06-08 07:26:56.716755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef77ede9bf45'
down_revision = '068ac36572fc'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_item',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_list.list_id'], ),
    sa.PrimaryKeyConstraint('list_id', 'item_id')
    )
    op.create_index(op.f('ix_list_item_item_id'), 'list_item', ['item_id'], unique=False)
    op.create_index(op.f('ix_list_item_list_id'), 'list_item', ['list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_list_item_list_id'), table_name='list_item')
    op.drop_index(op.f('ix_list_item_item_id'), table_name='list_item')
    op.drop_table('list_item')
    # ### end Alembic commands ###

