"""empty message

Revision ID: f2bb313c0aff
Revises: 16a1d43e73d1
Create Date: 2020-04-21 10:22:43.555609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2bb313c0aff'
down_revision = '16a1d43e73d1'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usr', 'hh_size',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=6),
               existing_nullable=True)
    op.alter_column('usr', 'marital_s',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('usr', 'no_adults',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=6),
               existing_nullable=True)
    op.alter_column('usr', 'no_kids',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=6),
               existing_nullable=True)
    op.alter_column('usr', 'sex',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade_cpstnpro():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usr', 'sex',
               existing_type=sa.String(length=6),
               type_=sa.CHAR(length=1),
               existing_nullable=True)
    op.alter_column('usr', 'no_kids',
               existing_type=sa.String(length=6),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('usr', 'no_adults',
               existing_type=sa.String(length=6),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('usr', 'marital_s',
               existing_type=sa.String(length=10),
               type_=sa.CHAR(length=1),
               existing_nullable=True)
    op.alter_column('usr', 'hh_size',
               existing_type=sa.String(length=6),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###

